config/routes.rb
Dialog::Application.routes.draw do
  resources :userlists

  resources :users

  get "dialog_input/select"
  get "dialog_input/selected"

   root 'top#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/userlist.rb
class Userlist < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dialog_input_controller.rb
class DialogInputController < ApplicationController
  def select

    fields = flashItem("default",params[:fields],"fields")
    fielddisps = flashItem("default",params[:fielddisps],"fieldsdisp")
    table = flashItem("table",params[:table],"table")
    search_text = flashItem("",params[:search_text],"search_text")
    field = flashItem("default",params[:field],"field")
    idfield = flashItem("default",params[:idfield],"idfield")
    group = flashItem("default",params[:group],"group")
    dpath = flashItem("default",params[:dpath],"dpath")
    diid = flashItem("default",params[:diid],"diid")
    fields = fields.split()
    fielddisps = fielddisps.split()
    sql = flashItem("default",params[:sql],"sql")
    sqlwhere = flashItem("defalut",params[:sqlwhere],"sqlwhere")

    if search_text == "" then
      selecteddata = Object.const_get(table).find_by_sql("#{sql} limit 1000;")
    else
      strfields = fields.join(",")
   #   fields.delete("id")
      strwhere = fields.join(" like '%#{search_text}%' or ")
      strwhere = strwhere + " like '%#{search_text}%'"
      strwhere = sqlwhere.gsub("@@",search_text) if sqlwhere != ""
      selecteddata = Object.const_get(table).find_by_sql("select #{strfields} from (#{sql}) as t where #{strwhere} limit 100;")
    end
    @search_text = search_text
    @selecteddata = selecteddata
    @fielddisps   =  fielddisps
    @fields       =  fields
    @table        =  table
    @idfield      =  idfield
    @group        =  group
    @dpath        =  dpath


=begin
    @str = ""
    @str = @str + "<input type='text' name='search_text' id='dialog_search_text' value='#{search_text}' />"
    @str = @str + "<input type='submit' value='送信' id='dialog_search_submit'/>"
    if  selecteddata.size == 1000 then
      @str = @str + " リスト内に表示出来ません。抽出してください。"
    end
    @str = @str + "<table id='select' >"
    @str = @str + "<tr>"
    fielddisps.each{|columname|
      @str = @str + "<th>"
      @str = @str + columname
      @str = @str + "</th>"
    }
    @str = @str + "</tr>"

    selecteddata.each{|data|
      @str = @str + "<tr class='dialog_line' >"
      fields.each{|colum|
        @str = @str + "<td class='dialog_itme' data-table='#{table}' data-idfield='#{idfield}' data-id='#{data[idfield]}' data-group='#{group}' >"
        @str = @str + data[colum].to_s
        @str = @str + "</td>"
      }
      @str = @str + "</tr>"
    }
    @str = @str + "</table>"
=end

  end
  def selected

    @diid = flashItem("default",params[:diid],"diid")
    @edialog = params[:edialog]

    sql = flashItem("default",params[:sql],"sql")
    #所属グループ
    @group = params[:group]
    @dpath = params[:dpath]
    #選択した情報
    @fields = nil
    @p_id   = params[:id]
    @idfield = params[:idfield]
    begin
      @fields = Object.const_get(params[:table]).find_by_sql("select * from (#{sql}) as t where #{params[:idfield]} = '#{params[:id]}' limit 1;")
      @field_first =  Object.const_get(params[:table]).find_by_sql("select * from (#{sql}) as t  limit 1;")
      #フィルド名リスト
      @fieldNames = []
        @field_first[0].attributes.keys.each{|column|
          @fieldNames << column
        }
    rescue

    end
  end
  private
  #値の取得
  #引数　default:デフォルト値
  #     paramsValue:paramsで受け取った値
  #     paramsName:内部的にflash[]で使われる名称
  def flashItem(default,paramsValue,paramsName)
    #params値に値が有る場合
    if paramsValue != nil then
      var = paramsValue
      flash[paramsName] = var
      #params値が無く、flashとしての保持データが有る場合
    elsif flash[paramsName] != nil then
      var = flash[paramsName]
      flash.keep[paramsName]
      #prams値とflashとしての保持データの両方が無い場合.(主に一番最初)
    else
      var = default
      flash[paramsName] = default
    end
    return var
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index

  end
end

app/controllers/userlists_controller.rb
class UserlistsController < ApplicationController
  before_action :set_userlist, only: [:show, :edit, :update, :destroy]

  # GET /userlists
  # GET /userlists.json
  def index
    @userlists = Userlist.all
  end

  # GET /userlists/1
  # GET /userlists/1.json
  def show
  end

  # GET /userlists/new
  def new
    @userlist = Userlist.new
  end

  # GET /userlists/1/edit
  def edit
  end

  # POST /userlists
  # POST /userlists.json
  def create
    @userlist = Userlist.new(userlist_params)

    respond_to do |format|
      if @userlist.save
        format.html { redirect_to @userlist, notice: 'Userlist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @userlist }
      else
        format.html { render action: 'new' }
        format.json { render json: @userlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userlists/1
  # PATCH/PUT /userlists/1.json
  def update
    respond_to do |format|
      if @userlist.update(userlist_params)
        format.html { redirect_to @userlist, notice: 'Userlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @userlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userlists/1
  # DELETE /userlists/1.json
  def destroy
    @userlist.destroy
    respond_to do |format|
      format.html { redirect_to userlists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userlist
      @userlist = Userlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userlist_params
      params.require(:userlist).permit(:code)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :phone, :code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/userlists_helper.rb
module UserlistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dialog_input/_select_disp.html.erb
<input type='text' name='search_text' id='dialog_search_text' value='<%= @search_text %>' data-dpath='<%= @dpath %>' />
<input type='submit' value='送信' id='dialog_search_submit' data-dpath='<%= @dpath %>'/>
<% if  @selecteddata.size == 1000 then %>
リスト内に表示出来ません。抽出してください。
<% end %>
<table id='select' >
  <tr>
    <% @fielddisps.each{|columname|  %>
      <th>
        <%= columname  %>
      </th>
    <% } %>
  </tr>

  <% @selecteddata.each{|data|  %>
    <tr class='dialog_line' >
    <% @fields.each{|colum| %>
      <td class='dialog_itme' data-table='<%= @table %>' data-idfield='<%= @idfield %>' data-id='<%= data[@idfield] %>' data-group='<%= @group %>' data-dpath='<%= @dpath %>' >
        <%= data[colum].to_s %>
      </td>
    <% } %>
  </tr>
  <% } %>
</table>

app/views/dialog_input/select.js.erb
$('#select_search').html();
//$('#select_table').html("<%=  raw(@str) %>");
$('#select_table').html("<%=  escape_javascript(render 'select_disp') %>");

$('#dialog_search_text').focus();

app/views/dialog_input/selected.js.erb
$('.dialoginput_g').each(function(){
    if($(this).attr('data-group') == <%= @group %>){
        <% if @fields.present? == false and @p_id.present? == true and @edialog != "false" then %>
          $('#alarm_dialog').dialog('open');
          $('#alarm_dialog').text("入力した値はみつかりません。");
          if($(this).attr('data-diid') == <%= @diid %>){
            $(this).focus();
        }
        <% end %>
        <% @fieldNames.each{|name|%>
        if($(this).attr('data-field') == "<%= name %>") {

            $(this).css("color","");
            $(this).text("<%= @fields[0][name] %>").change();
            $(this).val("<%= @fields[0][name] %>").change();
        }
        <% } if @fields.present? %>

        <% @fieldNames.each{|name|%>
          <% if name != @idfield then %>
            <% if @edialog == "false" then %>
                if($(this).attr('data-field') == "<%= name %>") {
                    $(this).css("color","red");
                    $(this).text("入力した値はみつかりません")
                    $(this).val("入力した値はみつかりません.")
                }
            <% else %>
                if($(this).attr('data-field') == "<%= name %>") {

                    $(this).css("color","");
                    $(this).text("")
                    $(this).val("")
                }
            <% end %>
          <% end %>
        <% } if @fields.blank?  %>


    }
    //if($(this).attr('data-diid') == <%#= @diid %>){
    //    $(this).focus();
    //}

    //次のフォーカスに移動させる
    //var elements = "input[type=text]";
    //var index = $(elements).index(this);
    //$(elements + ":gt(" + index + "):first").focus();
    //alert(elements + ":gt(" + index + "):first")

})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dialog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
      $(function() {
          $('.dialoginput_g').dialoginput('');
      });
  </script>
</head>
<body>

<%= yield %>

<div id="selected_dialog">
  <div id="select_search"></div>
  <div id="select_table"></div>
</div>
<div id="alarm_dialog" >
  <div id="alarm_text" ></div>
</div>
</body>
</html>

app/views/top/index.html.erb
<h1>top</h1>
<%= link_to "user作成",url_for(:action => :index,:controller => :users) %><br>
<%= link_to "user情報作成(作成、編集時にダイアログが表示されます)",url_for(:action => :index,:controller => :userlists) %>

app/views/userlists/_form.html.erb
<%= form_for(@userlist) do |f| %>
  <% if @userlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userlist.errors.count, "error") %> prohibited this userlist from being saved:</h2>

      <ul>
      <% @userlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%#= f.text_field :code %>
    <%= f.text_field :code,  :size => 4  ,
                     :class => "dialoginput dialoginput_g",
                     "data-field" => "code",
                     "data-group" => "1",
                     "data-diid" => "11",
                     "data-id" => "dialoginput_1",
                     "data-dpath" => "../../"%>
    <span id="dialoginput_1"
          data-sql="select name,phone,code from users  "
          data-sqlwhere=""
          data-table="User"
          data-idfield="code"
          data-fields="name phone code"
          data-fielddisps="name phone code"></span>
    <a class="dialoginput_g" data-field="name" data-group="1"><%= User.where(:code => @userlist.code).first.try("name") %></a>
    <button
            class="dialoginput dialoginput_g "
            data-diid="11"
            data-group="1"
            data-id="dialoginput_1"
            data-dpath = "../../"
            name="button"
            type="button">検索
    </button>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/userlists/edit.html.erb
<h1>Editing userlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @userlist %> |
<%= link_to 'Back', userlists_path %>

app/views/userlists/index.html.erb
<h1>Listing userlists</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @userlists.each do |userlist| %>
      <tr>
        <td><%= userlist.code %></td>
        <td><%= link_to 'Show', userlist %></td>
        <td><%= link_to 'Edit', edit_userlist_path(userlist) %></td>
        <td><%= link_to 'Destroy', userlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userlist', new_userlist_path %>

app/views/userlists/new.html.erb
<h1>New userlist</h1>

<%= render 'form' %>

<%= link_to 'Back', userlists_path %>

app/views/userlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @userlist.code %>
</p>

<%= link_to 'Edit', edit_userlist_path(@userlist) %> |
<%= link_to 'Back', userlists_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.phone %></td>
        <td><%= user.code %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Code:</strong>
  <%= @user.code %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>